<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>AppiumE2EFramework</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>AppiumE2EFramework</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <executionType>local</executionType>
        <executionArgLine></executionArgLine>
    </properties>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.10.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.appium/java-client -->
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>9.4.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.18.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.18.3</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.aventstack/extentreports -->
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>5.1.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.browserstack/browserstack-java-sdk -->
        <dependency>
            <groupId>com.browserstack</groupId>
            <artifactId>browserstack-java-sdk</artifactId>
            <version>1.30.9</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>


    <profiles>
        <!-- Dynamic ArgLine Injection Based on Execution Type -->
        <profile>
            <id>argline-cloud</id>
            <activation>
                <property>
                    <name>executionType</name>
                    <value>cloud</value>
                </property>
            </activation>
            <properties>
                <executionArgLine>-javaagent:/Users/asingadiwar/.m2/repository/com/browserstack/browserstack-java-sdk/1.30.9/browserstack-java-sdk-1.30.9.jar</executionArgLine>
            </properties>
        </profile>

        <profile>
            <id>argline-local</id>
            <activation>
                <property>
                    <name>executionType</name>
                    <value>local</value>
                </property>
            </activation>
            <properties>
                <executionArgLine></executionArgLine>
            </properties>
        </profile>

        <!-- Android Regression -->
        <profile>
            <id>Android-Regression</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.3</version>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>testSuites/testngAndroid.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>${executionArgLine}</argLine>
                            <systemPropertyVariables>
                                <executionType>${executionType}</executionType>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Android Smoke -->
        <profile>
            <id>Android-Smoke</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.3</version>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>testSuites/smokeTestngAndroid.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>${executionArgLine}</argLine>
                            <systemPropertyVariables>
                                <executionType>${executionType}</executionType>
                            </systemPropertyVariables>                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- iOS Regression -->
        <profile>
            <id>IOS-Regression</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.3</version>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>testSuites/testngIOS.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>${executionArgLine}</argLine>
                            <systemPropertyVariables>
                                <executionType>${executionType}</executionType>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
